version: '3.5'

services:
  nginx:
    image: ${REGISTRY_URL}/${PJPrefix}/nginx:latest
    platform: linux/x86_64
    container_name: ${PJPrefix}-nginx
    volumes:
      - ./docker/nginx/dev/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - laravel
  laravel:
    image: ${REGISTRY_URL}/${PJPrefix}/laravel:latest
    platform: linux/x86_64
    container_name: ${PJPrefix}-laravel
    depends_on:
      - mysql
    networks:
      - laravel
    volumes:
      - ./src:/application
    env_file:
      - ./src/.env
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: ${PJPrefix}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql-data:/var/lib/mysql:delegated
    networks:
      - laravel

networks:
  laravel:
    name: laravel
