version: '3.5'

services:
  nginx:
    image: ${REGISTRY_URL}/${PJPrefix}/build-nginx:latest
    platform: linux/x86_64
    container_name: ${PJPrefix}-nginx
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./src:/application
    depends_on:
      - mysql
    networks:
      - laravel
    env_file:
      - ./src/.env
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: ${PJPrefix}-mysql
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./storage/mysql-data:/var/lib/mysql:delegated
    networks:
      - laravel

networks:
  laravel:
    name: laravel
